# --------------------------------------------
# Basic Site Settings
# --------------------------------------------
locale                   : "en-GB"
site_theme               : "default"
title                    : "Kuan-Cheng (Louis) Chen"
title_separator          : "-"
name                     : &name "Kuan-Cheng (Louis) Chen"
description              : &description "Ph.D. candidate in Quantum Engineering at Imperial College London; research in distributed quantum-computing architectures, quantum ML & circuit optimisation."
url                      : https://louisanity.github.io          # ← GitHub Pages root
baseurl                  : ""                                   # "" means the site is served from the repo root
repository               : "Louisanity/academicpages.github.io" # ← your fork of the template

# --------------------------------------------
# Author profile (left-hand sidebar on the site)
# --------------------------------------------
author:
  # Biographic information
  avatar           : "profile.png"
  name             : "Louis Chen"
  pronouns         :            # add if you wish (e.g. "he/him")
  bio              : "Ph.D. candidate · Quantum Engineering · Imperial College London"
  location         : "London, UK"
  employer         : "Imperial College London"
  uri              : "https://profiles.imperial.ac.uk/kuan-cheng.chen17/about"
  email            : "kc2816@ic.ac.uk"

  # Academic profiles
  academia         :
  arxiv            :
  googlescholar    :
  impactstory      :
  orcid            :
  semantic         :
  pubmed           :
  researchgate     :
  scopus           :

  # Repositories & dev platforms
  github           : "Louisanity"
  bitbucket        :
  codepen          :
  dribbble         :
  kaggle           :
  stackoverflow    :

  # Social media
  bluesky          :
  linkedin         : "louis-chen-801214109"
  mastodon         :
  medium           :
  twitter          :
  youtube          :
  # leave any others blank

# --------------------------------------------
# Publication category headings (feel free to edit)
# --------------------------------------------
publication_category:
  books:
    title: "Books"
  manuscripts:
    title: "Journal Articles"
  conferences:
    title: "Conference Papers"

# --------------------------------------------
# Site-wide options (mostly left as defaults)
# --------------------------------------------
teaser                   :
breadcrumbs              : false
words_per_minute         : 160
future                   : true
read_more                : "disabled"
talkmap_link             : false

comments:
  provider               :
  disqus:      { shortname: "" }
  discourse:    { server: "" }
  facebook:     { appid: "", num_posts: "", colorscheme: "" }

staticman:
  allowedFields          : ['name','email','url','message']
  branch                 : "gh-pages"
  commitMessage          : "New comment."
  filename               : comment-{@timestamp}
  format                 : "yml"
  moderation             : true
  path                   : "_data/comments/{options.slug}"
  requiredFields         : ['name','email','message']
  transforms:            { email: "md5" }
  generatedFields:
    date:
      type               : "date"
      options:           { format: "iso8601" }

atom_feed:
  hide                   : false
  path                   :

# --------------------------------------------
# SEO / social-sharing / analytics (update later)
# --------------------------------------------
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :

twitter:   { username: &twitter }
facebook:  { username: "", app_id: "", publisher: "" }
og_image                 :

social:
  type                   : "Person"
  name                   : *name
  links:                 []   # e.g. ["https://github.com/Louisanity"]

analytics:
  provider               : "false"
  google:     { tracking_id: "" }

# --------------------------------------------
# Jekyll build - files to include / exclude
# --------------------------------------------
include: [".htaccess", "_pages", "files"]
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .github
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - CHANGELOG
  - Capfile
  - config
  - Dockerfile
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - local
  - log
  - node_modules
  - package.json*
  - Rakefile
  - README
  - tmp
  - vendor
keep_files: [".git", ".svn"]

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# --------------------------------------------
# Conversion / Markdown / Sass
# --------------------------------------------
markdown: kramdown
highlighter: rouge
excerpt_separator: "\n\n"
kramdown:
  input: GFM
  smart_quotes: lsquo,rsquo,ldquo,rdquo

sass:
  sass_dir: _sass
  style: compressed

# --------------------------------------------
# Collections, defaults, permalink, timezone
# --------------------------------------------
collections:
  teaching:     { output: true, permalink: /:collection/:path/ }
  publications: { output: true, permalink: /:collection/:path/ }
  portfolio:    { output: true, permalink: /:collection/:path/ }
  talks:        { output: true, permalink: /:collection/:path/ }

defaults:
  - scope:  { path: "", type: posts }
    values: { layout: single, author_profile: true, read_time: true, comments: true, share: true, related: true }
  - scope:  { path: "", type: pages }
    values: { layout: single, author_profile: true }
  - scope:  { path: "", type: teaching }
    values: { layout: single, author_profile: true, share: true, comments: true }
  - scope:  { path: "", type: publications }
    values: { layout: single, author_profile: true, share: true, comments: true }
  - scope:  { path: "", type: portfolio }
    values: { layout: single, author_profile: true, share: true, comment: true }
  - scope:  { path: "", type: talks }
    values: { layout: talk, author_profile: true, share: true }

permalink: /:categories/:title/
timezone : Europe/London     # you are based in London

# --------------------------------------------
# Plugins & whitelist (GitHub Pages-compatible)
# --------------------------------------------
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

whitelist: *plugins

# --------------------------------------------
# Archives, compression, etc. (unchanged)
# --------------------------------------------
category_archive: { type: liquid, path: /categories/ }
tag_archive:      { type: liquid, path: /tags/ }

compress_html:
  clippings: all
  ignore: { envs: development }
